name = "specimen"
version = "0.1.0"
defaultTargets = ["Specimen"]
testRunner = "SpecimenTest"
lintDriver = "batteries/runLinter"

[leanOptions]
linter.missingDocs = false

[[lean_lib]]
name = "SpecimenTest"

[[lean_lib]]
name = "Specimen"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "9acabf83fb0369d00ba2e2410ca68db581a96bcc"

[[require]]
name = "plausible"
scope = "leanprover-community"
rev = "v4.32.0"

[[require]]
name = "proofwidgets"
scope = "leanprover-community"
rev = "v0.0.96"